### ISSUE TITLE
Camera.bat Error

### ISSUE THREAD

**Issue by inferno46n2** [warmshao/FasterLivePortrait#108]
Hello,

I want to only retarget the eyes and mouth using a webcam + an image.

When I set the variables in the trt_infer.yaml file for eye retargeting and lip retargeting to True I get

no face in driving frame:1
Traceback (most recent call last):
File "C:\LivePort\run.py", line 276, in
run_with_video(args)
File "C:\LivePort\run.py", line 91, in run_with_video
dri_crop, out_crop, out_org, dri_motion_info = pipe.run(frame, pipe.src_imgs[0], pipe.src_infos[0],
File "C:\LivePort\src\pipelines\faster_live_portrait_pipeline.py", line 482, in run
combined_eye_ratio_tensor = self.calc_combined_eye_ratio(c_d_eyes_i,
File "C:\LivePort\src\pipelines\faster_live_portrait_pipeline.py", line 116, in calc_combined_eye_ratio
c_d_eyes_i = np.array(c_d_eyes_i).reshape(1, 1)
ValueError: cannot reshape array of size 2 into shape (1,1)
Error occurred during execution

**Comment by warmshao** [comment]
> no face in driving frame:1

Change the parameter animation_region instead of eye retargeting or lip retargeting.

**Comment by inferno46n2** [comment]
> > no face in driving frame:1
> 
> Change the parameter animation_region instead of eye retargeting or lip retargeting.

How do I add multiple ?

For example: animation_region: "lip, eyes"

**Comment by warmshao** [comment]
> > > no face in driving frame:1
> > 
> > 
> > Change the parameter animation_region instead of eye retargeting or lip retargeting.
> 
> How do I add multiple ?
> 
> For example: animation_region: "lip, eyes"

Not supported now
