### ISSUE TITLE
About Updating the Windows All-in-One Package

### ISSUE THREAD

**Issue by KeyStrokeVII** [warmshao/FasterLivePortrait#118]
I recently downloaded the Windows All-in-One Package for FasterLivePortrait from the release page. After unzipping it, I noticed that it doesn't include some of the latest updates available.

Could you please advise on the best way to update the package with the latest changes? I want to ensure I'm using the most current features and improvements.

Thank you for your assistance and for your work on this incredible project!

**Comment by warmshao** [comment]
download this bat file: https://github.com/warmshao/FasterLivePortrait/blob/master/update.bat, then double click to update latest code

**Comment by KeyStrokeVII** [comment]
![Screenshot 2024-12-22 143931](https://github.com/user-attachments/assets/2f98ca23-a9d5-4f3e-8bc2-7569aa676d87)

I am getting an error when i double click the update bat file.

**Comment by warmshao** [comment]
> ![Screenshot 2024-12-22 143931](https://private-user-images.githubusercontent.com/76645611/398008978-2f98ca23-a9d5-4f3e-8bc2-7569aa676d87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTU2MjUsIm5iZiI6MTczNDkxNTMyNSwicGF0aCI6Ii83NjY0NTYxMS8zOTgwMDg5NzgtMmY5OGNhMjMtYTlkNS00ZjNlLThiYzItNzU2OWFhNjc2ZDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAwNTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZTE4ZDExZWVmZGY1NmI4MGM3NzgxNzQ4Y2RmYTU3ODMwZTNmZTEzN2UyZGU5MzEzY2E5NTBhNzU0OTcwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D-8aBxlccVvZdYcD2uAiXdQnr1RoYUthKaevonxsO1o)
> 
> I am getting an error when i double click the update bat file.

put bat file in the root directory of fasterliveportrait

**Comment by KeyStrokeVII** [comment]
That's exactly what I did that gave me that error

**Comment by holycowdude** [comment]
Same error here

**Comment by motowntalent** [comment]
Same

**Comment by warmshao** [comment]
Hi,guys, another way to update: download the source code: https://github.com/warmshao/FasterLivePortrait/archive/refs/tags/v1.7.zip, unzip into the root of fasterliveportrait to replace the old files

**Comment by tivikoff** [comment]
Hi @warmshao , after updating with either 1.7 source code manual replace or using "git clone" the result exactly the same when running "app.bat", "webui.bat" or "camera.bat" - ir returns this log:

```
C:\Users\Admin\Neural\FasterLivePortrait>app.bat

C:\Users\Admin\Neural\FasterLivePortrait>.\venv\python.exe .\app.py --mode trt
INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.24 (you have 1.4.13). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
load Human Model >>>
loading model: warping_spade
{'name': 'WarpingSpadeModel', 'predict_type': 'trt', 'model_path': './checkpoints/liveportrait_onnx/warping_spade-fix.trt'}
[12/28/2024-04:06:58] [TRT] [E] 6: The engine plan file is generated on an incompatible device, expecting compute 7.5 got compute 8.6, please rebuild.
[12/28/2024-04:06:58] [TRT] [E] 2: [engine.cpp::nvinfer1::rt::deserializeEngine::990] Error Code 2: Internal Error (Assertion engine->deserialize(start, size, allocator, runtime) failed. )
Traceback (most recent call last):
  File "C:\Users\Admin\Neural\FasterLivePortrait\app.py", line 32, in <module>
    gradio_pipeline = GradioLivePortraitPipeline(infer_cfg)
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\pipelines\gradio_live_portrait_pipeline.py", line 36, in init
    super(GradioLivePortraitPipeline, self).init(cfg, **kwargs)
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\pipelines\faster_live_portrait_pipeline.py", line 28, in init
    self.init(**kwargs)
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\pipelines\faster_live_portrait_pipeline.py", line 32, in init
    self.init_models(**kwargs)
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\pipelines\faster_live_portrait_pipeline.py", line 72, in init_models
    self.model_dict[model_name] = getattr(models, self.cfg.models[model_name]["name"])(
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\models\warping_spade_model.py", line 20, in init
    super(WarpingSpadeModel, self).init(**kwargs)
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\models\base_model.py", line 13, in init
    self.predictor = get_predictor(**self.kwargs)
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\models\predictor.py", line 257, in get_predictor
    return TensorRTPredictor(**kwargs)
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\models\predictor.py", line 61, in init
    assert self.engine
AssertionError
Exception ignored in: <function TensorRTPredictor.del at 0x000001FC2F3F7BE0>
Traceback (most recent call last):
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\models\predictor.py", line 167, in del
    del self.context
AttributeError: context
Exception ignored in: <function BaseModel.del at 0x000001FC316F0280>
Traceback (most recent call last):
  File "C:\Users\Admin\Neural\FasterLivePortrait\src\models\base_model.py", line 48, in del
    if self.predictor is not None:
AttributeError: 'WarpingSpadeModel' object has no attribute 'predictor'
```

If trying to run "update.bat" as you offered in the first method it returns the same message as for other guys above:

```
C:\Users\Admin\Neural\FasterLivePortrait>update.bat
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Fatal error in launcher: Unable to create process using '"E:\public_projects\FasterLivePortrait-windows\venv\python.exe"  "C:\Users\Admin\Neural\FasterLivePortrait\venv\Scripts\pip.exe" install -r requirements.txt': The system cannot find the file specified.
```

And since it says it can't find git repository, I tried to add .git by using "git clone" in this folder and replacing the source files. Now the error log changed to this:

```
C:\Users\Admin\Neural\FasterLivePortrait>update.bat
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Fatal error in launcher: Unable to create process using '"E:\public_projects\FasterLivePortrait-windows\venv\python.exe"  "C:\Users\Admin\Neural\FasterLivePortrait\venv\Scripts\pip.exe" install -r requirements.txt': The system cannot find the file specified.
```

As you can see, both times this update.bat looking for specific directory `E:\public_projects\FasterLivePortrait-windows\venv\python.exe` which is exactly the same "third-party" path for everyone here, so looks like this path is somewhere in the code. 

But anyway, updating even without this update.bat doesn't solve this common issue.

**Comment by warmshao** [comment]
ok， I will upload new windows packages today

**Comment by warmshao** [comment]
Hi guys, you can download in https://github.com/warmshao/FasterLivePortrait/releases/tag/v1.8

**Comment by tivikoff** [comment]
Hi thank you for prompt fixes! Is it possible to upload win package on google drive (as previous one) or any other open cloud? Looks like Quark asking for chinese phone number for download if I translated this correctly

**Comment by holycowdude** [comment]
Thanks please can you upload the package on google drive?
I dont think its possible to download on Pan if your outside of china

**Comment by motowntalent** [comment]
Yes, pleas find an alternative download site. Perhaps Mega.

**Comment by warmshao** [comment]
I have uploaded it to HF, check  https://huggingface.co/warmshao/FasterLivePortrait-windows/resolve/main/FasterLivePortrait-windows-20241228.zip

**Comment by KeyStrokeVII** [comment]
> I have uploaded it to HF, check https://huggingface.co/warmshao/FasterLivePortrait-windows/resolve/main/FasterLivePortrait-windows-20241228.zip

Thanks so much for this

**Comment by KeyStrokeVII** [comment]
> I have uploaded it to HF, check https://huggingface.co/warmshao/FasterLivePortrait-windows/resolve/main/FasterLivePortrait-windows-20241228.zip

Has anyone successfully downloaded and used the newly updated Windows version? After unzipping the file, I noticed that it didn't include the 'all_onnx2trt.bat' file, which we are instructed to double-click to convert ONNX files. Additionally, it doesn't contain the 'app.bat' file, and I'm unsure how to proceed from here. Could you please provide instructions on how to use this software?

**Comment by holycowdude** [comment]
App.bat is missing so there is no way to start it
I tried extracting over the older build but it still doesn't work when I run app.bat

**Comment by tivikoff** [comment]
@KeyStrokeVII it's in "scripts/all_onnx2trt.bat" path now. 
It will not find external directories if you just run it from there. Instead, run cmd from root directory "FasterLivePortrait-windows/". and use this command: `scripts/all_onnx2trt.bat`
After conversion, it should run fine.

@holycowdude use webui.bat

**Comment by warmshao** [comment]
> @KeyStrokeVII it's in "scripts/all_onnx2trt.bat" path now. It will not find external directories if you just run it from there. Instead, run cmd from root directory "FasterLivePortrait-windows/". and use this command: `scripts/all_onnx2trt.bat` After conversion, it should run fine.
> 
> @holycowdude use webui.bat

yes，thanks！👍

**Comment by BowenL0218** [comment]
> > @KeyStrokeVII it's in "scripts/all_onnx2trt.bat" path now. It will not find external directories if you just run it from there. Instead, run cmd from root directory "FasterLivePortrait-windows/". and use this command: `scripts/all_onnx2trt.bat` After conversion, it should run fine.
> > @holycowdude use webui.bat
> 
> yes，thanks！👍

After downloading the 1228 package for windows and run the onnx2trt, still encountered the same error: > AttributeError: 'WarpingSpadeModel' object has no attribute 'predictor'. Anyone solved this issue?

**Comment by holycowdude** [comment]
Thanks working for me using use webui.bat
I didnt use scripts/all_onnx2trt.bat first, do I need to?

**Comment by warmshao** [comment]
> Thanks working for me using use webui.bat I didnt use scripts/all_onnx2trt.bat first, do I need to?

It should be necessary unless you have previously converted to TensorRT (TRT). You can check your checkpoints folder to see if there are any TRT files.

**Comment by warmshao** [comment]
> > > @KeyStrokeVII it's in "scripts/all_onnx2trt.bat" path now. It will not find external directories if you just run it from there. Instead, run cmd from root directory "FasterLivePortrait-windows/". and use this command: `scripts/all_onnx2trt.bat` After conversion, it should run fine.
> > > @holycowdude use webui.bat
> > 
> > 
> > yes，thanks！👍
> 
> After downloading the 1228 package for windows and run the onnx2trt, still encountered the same error: > AttributeError: 'WarpingSpadeModel' object has no attribute 'predictor'. Anyone solved this issue?

Show me more logs

**Comment by yakhyo** [comment]
When I run `update.bat` , gives error below:

```
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
Fatal error in launcher: Unable to create process using '"E:\public_projects\FasterLivePortrait-windows\venv\python.exe"  "C:\Users\yakhyokhuja\Desktop\FasterLivePortrait-windows-20241228\FasterLivePortrait-windows\venv\Scripts\pip.exe" install -r requirements.txt': The system cannot find the file specified.
```

Out of curiosity why simply don't provide the `avtivate` to use it as an environment?

**Comment by motowntalent** [comment]
The instructions/readme for the Windows package I think need some cleanup. There is no app.p webui.py is what we need to run. 
The all_onnx2trt.bat file is in another directory and needs to be copied to the root. I think along with the py file. 
The readme has the localhost incorrect. Should say port :7890

But after I did those things, I got it running.

**Comment by warmshao** [comment]
> The instructions/readme for the Windows package I think need some cleanup. There is no app.p webui.py is what we need to run. The all_onnx2trt.bat file is in another directory and needs to be copied to the root. I think along with the py file. The readme has the localhost incorrect. Should say port :7890
> 
> But after I did those things, I got it running.

I will update soon

**Comment by inferno46n2** [comment]
> @KeyStrokeVII it's in "scripts/all_onnx2trt.bat" path now. It will not find external directories if you just run it from there. Instead, run cmd from root directory "FasterLivePortrait-windows/". and use this command: `scripts/all_onnx2trt.bat` After conversion, it should run fine.
> 
> @holycowdude use webui.bat

You need to run it as .\scripts\all_onnx2trt.bat (with the period at the front for relative)

**Comment by warmshao** [comment]
guys, Text driven based on kokoro-82M also supported now

https://github.com/user-attachments/assets/f006bcdd-1edc-411c-90b1-46a8e71c1a79
