### ISSUE TITLE
AttributeError: Can't pickle local object 'context_decorator.<locals>.decorate_context'

### ISSUE THREAD

**Issue by rohitpaul24** [warmshao/FasterLivePortrait#131]
When using Source Video with Driving Audio with similar setting and input as in the video giving in the repo. It's giving:

update infer cfg source from /tmp/gradio/b6d86b726c0e6689c8facfb69adb973e245387e4/s12.jpeg to /tmp/gradio/f4fc96dd3f2b929c939b8914ce4defc8aac795d6/d11.mp4
update infer cfg driving from /tmp/gradio/14e13cbcdfc25b3fbd967de1434281e15200cc1b/test.wav to /tmp/gradio/50faab3efc09e6806662ac24c7288c4523acb881/a-01.wav
update infer cfg flag_relative_motion from True to True
update infer cfg flag_do_crop from True to True
update infer cfg flag_pasteback from True to True
update infer cfg driving_multiplier from 1 to 1
update infer cfg flag_stitching from True to True
update infer cfg flag_crop_driving_video from False to False
update infer cfg flag_video_editing_head_rotation from False to False
update crop cfg src_scale from 2.3 to 2.3
update crop cfg src_vx_ratio from 0 to 0
update crop cfg src_vy_ratio from -0.125 to -0.125
update crop cfg dri_scale from 2.2 to 2.2
update crop cfg dri_vx_ratio from 0 to 0
update crop cfg dri_vy_ratio from -0.1 to -0.1
update infer cfg driving_smooth_observation_variance from 1e-07 to 1e-07
update infer cfg animation_region from lip to lip
update infer cfg cfg_scale from 4 to 4
process source:/tmp/gradio/f4fc96dd3f2b929c939b8914ce4defc8aac795d6/d11.mp4 >>>>>>>>
100%|███████████████████████████████████████████████████████████████████████████████████████| 225/225 [00:06<00:00, 35.11it/s]
finish process source:/tmp/gradio/f4fc96dd3f2b929c939b8914ce4defc8aac795d6/d11.mp4 >>>>>>>>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1897, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
  File "/home/azureuser/liveportrait/FasterLivePortrait/webui.py", line 41, in gpu_wrapped_execute_video
    return gradio_pipeline.execute_video(*args, **kwargs)
  File "/home/azureuser/liveportrait/FasterLivePortrait/src/pipelines/gradio_live_portrait_pipeline.py", line 127, in execute_video
    video_path, video_path_concat, total_time = self.run_audio_driving(input_driving_path,
  File "/home/azureuser/liveportrait/FasterLivePortrait/src/pipelines/gradio_live_portrait_pipeline.py", line 378, in run_audio_driving
    pickle.dump(dri_motion_infos, fw)
AttributeError: Can't pickle local object 'context_decorator.<locals>.decorate_context'

**Comment by rohitpaul24** [comment]
When debugging found out that the
dri_motion_infos = self.joyvasa_pipe.gen_motion_sequence(driving_audio_path)
        is returning a function instead of the motion data
        
I am using the docker file to run the project

**Comment by warmshao** [comment]
> When debugging found out that the dri_motion_infos = self.joyvasa_pipe.gen_motion_sequence(driving_audio_path) is returning a function instead of the motion data
> 
> I am using the docker file to run the project

Maybe it is a inference_mode bug, update code and try again
