### ISSUE TITLE
Docker Error: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

### ISSUE THREAD

**Issue by husthzy** [warmshao/FasterLivePortrait#37]
This is the output:
```
(base) root@a2d7b9b1e3ab:~/FasterLivePortrait# python app.py --mode onnx
Traceback (most recent call last):
  File "/root/FasterLivePortrait/app.py", line 11, in <module>
    from src.pipelines.gradio_live_portrait_pipeline import GradioLivePortraitPipeline
  File "/root/FasterLivePortrait/src/pipelines/gradio_live_portrait_pipeline.py", line 15, in <module>
    from .faster_live_portrait_pipeline import FasterLivePortraitPipeline
  File "/root/FasterLivePortrait/src/pipelines/faster_live_portrait_pipeline.py", line 13, in <module>
    from .. import models
  File "/root/FasterLivePortrait/src/models/__init__.py", line 7, in <module>
    from .warping_spade_model import WarpingSpadeModel
  File "/root/FasterLivePortrait/src/models/warping_spade_model.py", line 8, in <module>
    from .base_model import BaseModel
  File "/root/FasterLivePortrait/src/models/base_model.py", line 10, in <module>
    from .predictor import get_predictor
  File "/root/FasterLivePortrait/src/models/predictor.py", line 23, in <module>
    import pycuda.driver as cuda
  File "/root/miniconda3/lib/python3.10/site-packages/pycuda/driver.py", line 66, in <module>
    from pycuda._driver import *  # noqa
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

**Comment by warmshao** [comment]
ref: https://github.com/warmshao/FasterLivePortrait/issues/8

**Comment by husthzy** [comment]
It's OK now. Thanks!
