### ISSUE TITLE
FasterLivePortrait-windows-20240724 not working

### ISSUE THREAD

**Issue by nitinmukesh** [warmshao/FasterLivePortrait#42]
1. Downloaded and extracted the package
2. all_onnx2trt.bat
3. app.bat

```
Microsoft Windows [Version 10.0.22631.3958]
(c) Microsoft Corporation. All rights reserved.

C:\usable\FasterLivePortrait-windows-20240724>app.bat

C:\usable\FasterLivePortrait-windows-20240724>.\venv\python.exe .\app.py --mode trt
Traceback (most recent call last):
  File "C:\usable\FasterLivePortrait-windows-20240724\app.py", line 11, in <module>
    from src.pipelines.gradio_live_portrait_pipeline import GradioLivePortraitPipeline
  File "C:\usable\FasterLivePortrait-windows-20240724\src\pipelines\gradio_live_portrait_pipeline.py", line 16, in <module>
    from .faster_live_portrait_pipeline import FasterLivePortraitPipeline
  File "C:\usable\FasterLivePortrait-windows-20240724\src\pipelines\faster_live_portrait_pipeline.py", line 16, in <module>
    from .. import models
  File "C:\usable\FasterLivePortrait-windows-20240724\src\models\__init__.py", line 7, in <module>
    from .warping_spade_model import WarpingSpadeModel
  File "C:\usable\FasterLivePortrait-windows-20240724\src\models\warping_spade_model.py", line 8, in <module>
    from .base_model import BaseModel
  File "C:\usable\FasterLivePortrait-windows-20240724\src\models\base_model.py", line 10, in <module>
    from .predictor import get_predictor
  File "C:\usable\FasterLivePortrait-windows-20240724\src\models\predictor.py", line 11, in <module>
    import onnxruntime
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed.

C:\usable\FasterLivePortrait-windows-20240724>
```

I noticed the virtual environment does not have activate
venv\scripts\activate

**Comment by warmshao** [comment]
Have you installed CUDA and cuDNN on your computer?

**Comment by warmshao** [comment]
> File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py"

btw, File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\onnxruntime\__init__.py" this is not my provided python environment

**Comment by warmshao** [comment]
Although this is not an issue with the Python environment I provided, you can resolve it by using the command conda install conda-forge::vs2015_runtime.
